#!/usr/bin/env bash
# Branch cleanup report generator (report-only — never deletes).
# Implements docs/plans/branch-cleanup-report-gate.md.
#
# Scope: remote branches with a merged PR whose ref still exists.
# Never-PR'd and closed-unmerged branches are out of scope (separate tracks).
#
# Output: DELETE_CANDIDATE / RETAIN / REVIEW_REQUIRED classification per
# branch, written to artifacts/branch-cleanup-report-<date>.md (untracked).
# This script must never call `git push origin --delete` or equivalent.

set -euo pipefail
cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"

DATE_TAG="$(date +%F)"
OUT="artifacts/branch-cleanup-report-${DATE_TAG}.md"
mkdir -p artifacts
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "== Fetching origin =="
git fetch origin --prune --quiet

echo "== Enumerating merged PRs =="
gh pr list --state merged --limit 500 \
  --json headRefName,number,mergedAt,mergeCommit,baseRefName \
  > "$TMPDIR/merged_prs.json"

echo "== Enumerating remote branches =="
git for-each-ref --format='%(refname:short)' refs/remotes/origin \
  | sed 's#^origin/##' | grep -v '^HEAD$' | grep -v '^main$' \
  | sort -u > "$TMPDIR/all_branches.txt"

jq -r '.[].headRefName' "$TMPDIR/merged_prs.json" | sort -u > "$TMPDIR/merged_branch_names.txt"

# Candidate pool: merged-PR branches whose ref still exists.
comm -12 "$TMPDIR/merged_branch_names.txt" "$TMPDIR/all_branches.txt" > "$TMPDIR/candidates.txt"
CANDIDATE_COUNT=$(wc -l < "$TMPDIR/candidates.txt")
echo "Candidate pool (merged PR + branch present): $CANDIDATE_COUNT"

# --- Corpus locations for scans (full tree, not just LATEST/STATUS) ---
CORPUS_DIRS=(docs scripts config)

echo "== Building orphan-risk SHA set (cited in corpus, valid commit, not ancestor of main) =="
grep -rhoE '\b[0-9a-f]{7,40}\b' "${CORPUS_DIRS[@]}" 2>/dev/null | sort -u > "$TMPDIR/all_tokens.txt"
: > "$TMPDIR/orphan_risk_shas.txt"
while read -r tok; do
  # Skip tokens shorter than 7 hex chars in effect (regex already enforces) and pure-zero placeholders
  [[ "$tok" =~ ^0+$ ]] && continue
  if git cat-file -e "${tok}^{commit}" 2>/dev/null; then
    if ! git merge-base --is-ancestor "$tok" origin/main 2>/dev/null; then
      echo "$tok" >> "$TMPDIR/orphan_risk_shas.txt"
    fi
  fi
done < "$TMPDIR/all_tokens.txt"
ORPHAN_RISK_COUNT=$(wc -l < "$TMPDIR/orphan_risk_shas.txt" || echo 0)
echo "Corpus-cited commits not reachable from main: $ORPHAN_RISK_COUNT"

# --- Closed-arc / tag family keywords (from STATUS.md's own Closed arcs table
#     and tag names — kept as an explicit, editable list, not inferred) ---
CLOSED_ARC_KEYWORDS='claude-watch-parity|claude-gate|chroma-reconcile|pinwheel|codeql|runway-ledger|agent-run'
ACTIVE_ARC_KEYWORDS='codex-jsonl|trapdoor|issue-286|issue-268|judgebench|shadow-ledger|r2b|cg2|recovery-authority|naturalistic|portland|openclaw'

TAG_LIST="$(git tag)"

{
  echo "# Branch cleanup report — $DATE_TAG"
  echo
  echo "Generated by \`scripts/branch-cleanup-report.sh\`. Report-only — no branch was deleted."
  echo
  echo "Candidate pool: $CANDIDATE_COUNT branches (merged PR, ref still present)."
  echo "Corpus-cited commits unreachable from main (orphan-risk set): $ORPHAN_RISK_COUNT."
  echo
} > "$OUT"

DELETE_COUNT=0
REVIEW_COUNT=0
FAST_PASS_LIST="$TMPDIR/fast_pass.txt"
: > "$FAST_PASS_LIST"

echo "== Stage 1: fast checks (git + corpus grep + SHA provenance + family/arc keywords) =="
while read -r branch; do
  reasons=()

  pr_row=$(jq -c --arg b "$branch" '[.[] | select(.headRefName==$b)][0]' "$TMPDIR/merged_prs.json")
  pr_num=$(echo "$pr_row" | jq -r '.number')
  base_ref=$(echo "$pr_row" | jq -r '.baseRefName')
  merged_at=$(echo "$pr_row" | jq -r '.mergedAt')
  merge_sha=$(echo "$pr_row" | jq -r '.mergeCommit.oid')
  branch_tip=$(git rev-parse "origin/$branch" 2>/dev/null || echo "")

  # F. Merge target verification
  if [[ "$base_ref" != "main" ]]; then
    reasons+=("base ref was '$base_ref', not main")
  fi
  if ! git merge-base --is-ancestor "$merge_sha" origin/main 2>/dev/null; then
    reasons+=("merge commit $merge_sha is not reachable from current main")
  fi

  # Merge-history classification (informational, drives scrutiny not skip)
  if [[ -n "$branch_tip" ]] && git merge-base --is-ancestor "$branch_tip" origin/main 2>/dev/null; then
    merge_kind="history-preserved (ff/merge-commit)"
  else
    merge_kind="squash-or-rewritten (branch history off main)"
  fi

  # Age (days since merge)
  merged_epoch=$(date -d "$merged_at" +%s 2>/dev/null || echo 0)
  now_epoch=$(date +%s)
  age_days=$(( (now_epoch - merged_epoch) / 86400 ))
  if (( age_days < 30 )); then
    reasons+=("only $age_days days since merge (<30)")
  fi

  # Full corpus name scan
  hits=$(grep -rl -- "$branch" "${CORPUS_DIRS[@]}" 2>/dev/null || true)
  if [[ -n "$hits" ]]; then
    hit_files=$(echo "$hits" | tr '\n' ';' )
    reasons+=("name cited in: $hit_files")
  fi

  # SHA provenance: is any orphan-risk SHA an ancestor of this branch?
  if [[ -n "$branch_tip" && -s "$TMPDIR/orphan_risk_shas.txt" ]]; then
    while read -r sha; do
      if git merge-base --is-ancestor "$sha" "origin/$branch" 2>/dev/null; then
        reasons+=("cites unreachable-from-main commit $sha")
      fi
    done < "$TMPDIR/orphan_risk_shas.txt"
  fi

  # Tag/family + active-arc keyword match (conservative substring match)
  if echo "$branch" | grep -qiE "$CLOSED_ARC_KEYWORDS"; then
    reasons+=("matches a closed-arc/tag family keyword — tag coverage is not proven exhaustive")
  fi
  if echo "$branch" | grep -qiE "$ACTIVE_ARC_KEYWORDS"; then
    reasons+=("matches an active-arc keyword")
  fi

  {
    echo "## \`$branch\`"
    echo "- PR: #$pr_num  base: $base_ref  merged: $merged_at ($age_days days ago)"
    echo "- Merge method: $merge_kind"
    if [[ ${#reasons[@]} -eq 0 ]]; then
      echo "- Fast-gate result: CLEAN — queued for Stage 2 (convmem corpus check)"
      echo "$branch" >> "$FAST_PASS_LIST"
    else
      echo "- Fast-gate result: REVIEW_REQUIRED"
      for r in "${reasons[@]}"; do echo "  - $r"; done
      REVIEW_COUNT=$((REVIEW_COUNT+1))
    fi
    echo
  } >> "$OUT"
done < "$TMPDIR/candidates.txt"

FAST_PASS_COUNT=$(wc -l < "$FAST_PASS_LIST" || echo 0)
echo "Stage 1 clean (queued for convmem check): $FAST_PASS_COUNT / $CANDIDATE_COUNT"

echo "== Stage 2: convmem corpus check (only for Stage-1-clean branches) =="
{
  echo "---"
  echo "## Stage 2 results (convmem search — only run for Stage-1-clean branches)"
  echo
} >> "$OUT"

while read -r branch; do
  [[ -z "$branch" ]] && continue
  slug="${branch#*/}"
  result=$(convmem "$slug" --format json 2>/dev/null || convmem "$slug" 2>/dev/null || echo "SEARCH_FAILED")
  if [[ "$result" == "SEARCH_FAILED" ]] || echo "$result" | grep -qi "no results\|0 result"; then
    echo "### \`$branch\` — CLASSIFICATION: DELETE_CANDIDATE" >> "$OUT"
    echo "- convmem search: clean (no results, or search unavailable — see completeness caveat below)" >> "$OUT"
    echo "" >> "$OUT"
    DELETE_COUNT=$((DELETE_COUNT+1))
  else
    echo "### \`$branch\` — CLASSIFICATION: REVIEW_REQUIRED" >> "$OUT"
    echo "- convmem search returned results — human must confirm relevance before deletion" >> "$OUT"
    echo "" >> "$OUT"
    REVIEW_COUNT=$((REVIEW_COUNT+1))
  fi
done < "$FAST_PASS_LIST"

{
  echo "---"
  echo "## Summary"
  echo "- Candidate pool: $CANDIDATE_COUNT"
  echo "- DELETE_CANDIDATE: $DELETE_COUNT"
  echo "- REVIEW_REQUIRED: $REVIEW_COUNT"
  echo
  echo "**Completeness caveat:** a clean convmem search result is evidence of absence,"
  echo "not proof — the corpus is not guaranteed complete (see \`convmem doctor\`'s"
  echo "\`synthesis_gate\`/ingest-degraded warnings). DELETE_CANDIDATE classifications"
  echo "above still require Ryan's explicit per-batch approval and a pre-delete"
  echo "\`git bundle\` snapshot (verified restorable) before any ref is removed."
  echo
  echo "No branch was deleted by this script."
} >> "$OUT"

echo
echo "Report written to $OUT"
echo "DELETE_CANDIDATE: $DELETE_COUNT   REVIEW_REQUIRED: $REVIEW_COUNT   (of $CANDIDATE_COUNT candidates)"
